//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSExampleApp.Forms.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PSExampleApp.Forms.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo(s).
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD USER.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin mode.
        /// </summary>
        public static string AdminMode {
            get {
                return ResourceManager.GetString("AdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin options.
        /// </summary>
        public static string AdminOptionsHeader {
            get {
                return ResourceManager.GetString("AdminOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please allow bluetooth persmission to start scanning..
        /// </summary>
        public static string Alert_AllowBluetooth {
            get {
                return ResourceManager.GetString("Alert_AllowBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background succesfully saved, please restart the application for the changes to take effect..
        /// </summary>
        public static string Alert_BackgroundSaved {
            get {
                return ResourceManager.GetString("Alert_BackgroundSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable Bluetooth reader in order to start a measurement..
        /// </summary>
        public static string Alert_BluetoothDescription {
            get {
                return ResourceManager.GetString("Alert_BluetoothDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        public static string Alert_BluetoothTitle {
            get {
                return ResourceManager.GetString("Alert_BluetoothTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error taking photo, please check the app camera permission..
        /// </summary>
        public static string Alert_CameraPermission {
            get {
                return ResourceManager.GetString("Alert_CameraPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to device failed. Please try again.
        /// </summary>
        public static string Alert_ConnectionFailed {
            get {
                return ResourceManager.GetString("Alert_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device incompatible. Please select a different device.
        /// </summary>
        public static string Alert_DeviceIncompatible {
            get {
                return ResourceManager.GetString("Alert_DeviceIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering devices failed. Retrying to start the scanner..
        /// </summary>
        public static string Alert_DiscoverFailed {
            get {
                return ResourceManager.GetString("Alert_DiscoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with deleting the measurement please reload the list.
        /// </summary>
        public static string Alert_ErrorDeleteMeasurement {
            get {
                return ResourceManager.GetString("Alert_ErrorDeleteMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading the measurement, if the problem persist please restart the app.
        /// </summary>
        public static string Alert_ErrorLoadingMeasurement {
            get {
                return ResourceManager.GetString("Alert_ErrorLoadingMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed deleting the analyte. Please restart the application if the problem persists..
        /// </summary>
        public static string Alert_FailedDeleteAnalyte {
            get {
                return ResourceManager.GetString("Alert_FailedDeleteAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed importing the image. Please check if the image file has the correct format..
        /// </summary>
        public static string Alert_FailedImageImport {
            get {
                return ResourceManager.GetString("Alert_FailedImageImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import file. Permissions not set..
        /// </summary>
        public static string Alert_FailedImport {
            get {
                return ResourceManager.GetString("Alert_FailedImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed importing analyte. Please check if the json file has the correct format..
        /// </summary>
        public static string Alert_FailedImportAnalyte {
            get {
                return ResourceManager.GetString("Alert_FailedImportAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed importing the method. Please check if the method file has the correct format..
        /// </summary>
        public static string Alert_FailedImportMethod {
            get {
                return ResourceManager.GetString("Alert_FailedImportMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must have only one scan..
        /// </summary>
        public static string Alert_MethodIncompatibleNumberOfScans {
            get {
                return ResourceManager.GetString("Alert_MethodIncompatibleNumberOfScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to load the method. Please reinstall the app..
        /// </summary>
        public static string Alert_MethodNotFound {
            get {
                return ResourceManager.GetString("Alert_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method succesfully saved..
        /// </summary>
        public static string Alert_MethodSaved {
            get {
                return ResourceManager.GetString("Alert_MethodSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to a device, please try reconnecting to a device again..
        /// </summary>
        public static string Alert_NotConnected {
            get {
                return ResourceManager.GetString("Alert_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid psmethod file..
        /// </summary>
        public static string Alert_SelectValidMethodFile {
            get {
                return ResourceManager.GetString("Alert_SelectValidMethodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with starting a measurement please restart the device and try again.
        /// </summary>
        public static string Alert_SomethingWrong {
            get {
                return ResourceManager.GetString("Alert_SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title configured, please restart the application for the changes to take effect..
        /// </summary>
        public static string Alert_TitleConfigured {
            get {
                return ResourceManager.GetString("Alert_TitleConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a valid username..
        /// </summary>
        public static string Alert_ValidUserName {
            get {
                return ResourceManager.GetString("Alert_ValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active user cannot be deleted..
        /// </summary>
        public static string AlertActiveUserCannotBeDeleted {
            get {
                return ResourceManager.GetString("AlertActiveUserCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user with all it&apos;s measurements?.
        /// </summary>
        public static string AlertRemoveUserDescription {
            get {
                return ResourceManager.GetString("AlertRemoveUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        public static string AlertRemoveUserTitle {
            get {
                return ResourceManager.GetString("AlertRemoveUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZING SAMPLE.
        /// </summary>
        public static string AnalyzingSample {
            get {
                return ResourceManager.GetString("AnalyzingSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user.
        /// </summary>
        public static string ChangeUser {
            get {
                return ResourceManager.GetString("ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure analyte.
        /// </summary>
        public static string ConfigureAnalyte {
            get {
                return ResourceManager.GetString("ConfigureAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import or remove analyte.
        /// </summary>
        public static string ConfigureAnalyteHeader {
            get {
                return ResourceManager.GetString("ConfigureAnalyteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure app.
        /// </summary>
        public static string ConfigureApp {
            get {
                return ResourceManager.GetString("ConfigureApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure background.
        /// </summary>
        public static string ConfigureBackground {
            get {
                return ResourceManager.GetString("ConfigureBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure method.
        /// </summary>
        public static string ConfigureMethod {
            get {
                return ResourceManager.GetString("ConfigureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure title.
        /// </summary>
        public static string ConfigureTitle {
            get {
                return ResourceManager.GetString("ConfigureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to device.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting...
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Report...
        /// </summary>
        public static string CreatingReport {
            get {
                return ResourceManager.GetString("CreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix sample with buffer and add droplet.
        /// </summary>
        public static string DropSenseHeader {
            get {
                return ResourceManager.GetString("DropSenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new title.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS Example App.
        /// </summary>
        public static string ExampleAppTitle {
            get {
                return ResourceManager.GetString("ExampleAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found:.
        /// </summary>
        public static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on the reader to start a measurement.
        /// </summary>
        public static string HomePageHeader {
            get {
                return ResourceManager.GetString("HomePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Analyte.
        /// </summary>
        public static string ImportAnalyte {
            get {
                return ResourceManager.GetString("ImportAnalyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert sensor and wait for the indicator to turn BLUE.
        /// </summary>
        public static string InsertSensorHeader {
            get {
                return ResourceManager.GetString("InsertSensorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known analytes.
        /// </summary>
        public static string KnownAnalytes {
            get {
                return ResourceManager.GetString("KnownAnalytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement History.
        /// </summary>
        public static string MeasurementHistory {
            get {
                return ResourceManager.GetString("MeasurementHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        public static string Nederlands {
            get {
                return ResourceManager.GetString("Nederlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a psmethod file.
        /// </summary>
        public static string Picker_SelectMethodFile {
            get {
                return ResourceManager.GetString("Picker_SelectMethodFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESULT FOR.
        /// </summary>
        public static string ResultFor {
            get {
                return ResourceManager.GetString("ResultFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Measurement.
        /// </summary>
        public static string RunMeasurement {
            get {
                return ResourceManager.GetString("RunMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample name.
        /// </summary>
        public static string SampleName {
            get {
                return ResourceManager.GetString("SampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an analyte.
        /// </summary>
        public static string SelectAnalyteHeader {
            get {
                return ResourceManager.GetString("SelectAnalyteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectDeviceHeader {
            get {
                return ResourceManager.GetString("SelectDeviceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user from the list or create a new user.
        /// </summary>
        public static string SelectOrCreateUser {
            get {
                return ResourceManager.GetString("SelectOrCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} readers found, 
        ///please select:.
        /// </summary>
        public static string SelectPageMultipleReaders {
            get {
                return ResourceManager.GetString("SelectPageMultipleReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 reader found,  
        ///please select:.
        /// </summary>
        public static string SelectPageReaderFound {
            get {
                return ResourceManager.GetString("SelectPageReaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user to continue.
        /// </summary>
        public static string SelectUserHeader {
            get {
                return ResourceManager.GetString("SelectUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Report.
        /// </summary>
        public static string ShareReport {
            get {
                return ResourceManager.GetString("ShareReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plot.
        /// </summary>
        public static string ShowPlot {
            get {
                return ResourceManager.GetString("ShowPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        public static string StatusBarConnected {
            get {
                return ResourceManager.GetString("StatusBarConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string StatusBarConnecting {
            get {
                return ResourceManager.GetString("StatusBarConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string StatusBarDisconnected {
            get {
                return ResourceManager.GetString("StatusBarDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} readers found.
        /// </summary>
        public static string StatusBarMultipleReaders {
            get {
                return ResourceManager.GetString("StatusBarMultipleReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 reader found.
        /// </summary>
        public static string StatusBarReaderFound {
            get {
                return ResourceManager.GetString("StatusBarReaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
